version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci

  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
