
import 'package:flutter/foundation.dart';

import '../config/config.dart';
import '../models/ar_config.dart';
import '../services/backend_api_service.dart';

class ArtworkArConfigState {
  ArMarkerMode markerMode;
  bool isLoading;
  String? error;
  ArConfig? config;

  Uint8List? pendingUploadBytes;
  String? pendingUploadFileName;

  ArtworkArConfigState({
    this.markerMode = ArMarkerMode.autoGenerated,
    this.isLoading = false,
    this.error,
    this.config,
    this.pendingUploadBytes,
    this.pendingUploadFileName,
  });
}

class ArtworkArConfigProvider extends ChangeNotifier {
  final BackendApiService _api;
  final Map<String, ArtworkArConfigState> _byArtworkId = {};

  ArtworkArConfigProvider({BackendApiService? api}) : _api = api ?? BackendApiService();

  ArtworkArConfigState stateFor(String artworkId) {
    final id = artworkId.trim();
    if (id.isEmpty) return ArtworkArConfigState();
    return _byArtworkId.putIfAbsent(id, () => ArtworkArConfigState());
  }

  void clearState(String artworkId) {
    _byArtworkId.remove(artworkId.trim());
    notifyListeners();
  }

  void setMarkerMode(String artworkId, ArMarkerMode mode) {
    final state = stateFor(artworkId);
    if (state.markerMode == mode) return;
    state.markerMode = mode;
    state.error = null;
    notifyListeners();
  }

  void setPendingUpload({
    required String artworkId,
    required Uint8List bytes,
    required String fileName,
  }) {
    final state = stateFor(artworkId);
    state.pendingUploadBytes = bytes;
    state.pendingUploadFileName = fileName;
    state.error = null;
    notifyListeners();
  }

  void clearPendingUpload(String artworkId) {
    final state = stateFor(artworkId);
    state.pendingUploadBytes = null;
    state.pendingUploadFileName = null;
    notifyListeners();
  }

  Future<void> loadExisting({
    required String artworkId,
    required String arConfigId,
  }) async {
    final state = stateFor(artworkId);
    if (state.isLoading) return;

    state.isLoading = true;
    state.error = null;
    notifyListeners();

    try {
      final data = await _api.getArContent(arConfigId: arConfigId);
      if (data == null) {
        state.error = 'Failed to load AR config.';
        return;
      }
      state.config = ArConfig.fromJson(data);
      state.markerMode = state.config!.markerMode;
    } catch (e) {
      AppConfig.debugPrint('ArtworkArConfigProvider.loadExisting failed: $e');
      state.error = 'Failed to load AR config.';
    } finally {
      state.isLoading = false;
      notifyListeners();
    }
  }

  Future<void> autogenerateMarker({
    required String artworkId,
    required String walletAddress,
    String? subjectColor,
    int? markerSizePx,
    bool regenerate = false,
  }) async {
    final state = stateFor(artworkId);
    if (state.isLoading) return;

    state.isLoading = true;
    state.error = null;
    notifyListeners();

    try {
      final data = await _api.autogenerateArMarker(
        artworkId: artworkId,
        walletAddress: walletAddress,
        subjectColor: subjectColor,
        markerSizePx: markerSizePx,
        regenerate: regenerate,
      );
      if (data == null) {
        state.error = 'Failed to generate marker.';
        return;
      }
      state.config = ArConfig.fromJson(data);
      state.markerMode = state.config!.markerMode;
    } catch (e) {
      AppConfig.debugPrint('ArtworkArConfigProvider.autogenerateMarker failed: $e');
      state.error = 'Failed to generate marker.';
    } finally {
      state.isLoading = false;
      notifyListeners();
    }
  }

  Future<void> uploadMarker({
    required String artworkId,
    required String walletAddress,
  }) async {
    final state = stateFor(artworkId);
    final bytes = state.pendingUploadBytes;
    final name = state.pendingUploadFileName;
    if (bytes == null || bytes.isEmpty) {
      state.error = 'Please select a PNG file first.';
      notifyListeners();
      return;
    }
    if (name == null || name.trim().isEmpty) {
      state.error = 'Invalid file name.';
      notifyListeners();
      return;
    }
    if (state.isLoading) return;

    state.isLoading = true;
    state.error = null;
    notifyListeners();

    try {
      final data = await _api.uploadArMarker(
        artworkId: artworkId,
        walletAddress: walletAddress,
        fileBytes: bytes,
        fileName: name,
      );
      if (data == null) {
        state.error = 'Failed to upload marker.';
        return;
      }
      state.config = ArConfig.fromJson(data);
      state.markerMode = state.config!.markerMode;
      state.pendingUploadBytes = null;
      state.pendingUploadFileName = null;
    } catch (e) {
      AppConfig.debugPrint('ArtworkArConfigProvider.uploadMarker failed: $e');
      state.error = 'Failed to upload marker.';
    } finally {
      state.isLoading = false;
      notifyListeners();
    }
  }

  Future<void> finalize({
    required String artworkId,
    required String walletAddress,
  }) async {
    final state = stateFor(artworkId);
    final arConfigId = state.config?.id.trim();
    if (arConfigId == null || arConfigId.isEmpty) return;
    if (state.isLoading) return;

    state.isLoading = true;
    state.error = null;
    notifyListeners();

    try {
      final updated = await _api.updateArConfig(
        arConfigId: arConfigId,
        walletAddress: walletAddress,
        status: 'READY',
      );
      if (updated != null) {
        state.config = ArConfig.fromJson(updated);
      }
    } catch (e) {
      AppConfig.debugPrint('ArtworkArConfigProvider.finalize failed: $e');
      state.error = 'Failed to save AR configuration.';
    } finally {
      state.isLoading = false;
      notifyListeners();
    }
  }
}

