import 'artwork.dart';

enum ArMarkerMode {
  autoGenerated,
  userUploaded,
}

extension ArMarkerModeApi on ArMarkerMode {
  String get apiValue {
    switch (this) {
      case ArMarkerMode.autoGenerated:
        return 'AUTO_GENERATED';
      case ArMarkerMode.userUploaded:
        return 'USER_UPLOADED';
    }
  }

  static ArMarkerMode fromApiValue(String? value) {
    final normalized = (value ?? '').trim().toUpperCase();
    switch (normalized) {
      case 'USER_UPLOADED':
        return ArMarkerMode.userUploaded;
      case 'AUTO_GENERATED':
      default:
        return ArMarkerMode.autoGenerated;
    }
  }
}

class ArConfig {
  final String id;
  final String artworkId;
  final ArMarkerMode markerMode;
  final String? markerAssetUrl;
  final Map<String, dynamic>? markerMeta;
  final ArtworkArStatus status;

  const ArConfig({
    required this.id,
    required this.artworkId,
    required this.markerMode,
    this.markerAssetUrl,
    this.markerMeta,
    this.status = ArtworkArStatus.none,
  });

  factory ArConfig.fromJson(Map<String, dynamic> json) {
    final id = (json['arConfigId'] ?? json['id'] ?? '').toString();
    final artworkId = (json['artworkId'] ?? json['artwork_id'] ?? '').toString();
    return ArConfig(
      id: id,
      artworkId: artworkId,
      markerMode: ArMarkerModeApi.fromApiValue(json['markerMode']?.toString() ?? json['marker_mode']?.toString()),
      markerAssetUrl: json['markerAssetUrl']?.toString() ?? json['marker_asset_url']?.toString(),
      markerMeta: (json['markerMeta'] is Map) ? Map<String, dynamic>.from(json['markerMeta'] as Map) : null,
      status: ArtworkArStatusApi.fromApiValue(json['status']?.toString() ?? json['ar_status']?.toString()),
    );
  }
}

