import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:art_kubus/services/node/node_identity_proof.dart';
import 'package:flutter_test/flutter_test.dart';

/// Verification of a Node's identity proof, against a signature the real Node
/// produced.
///
/// The fixture is generated by the actual TypeScript implementation
/// (`kubus-node/src/identity/identityProof.ts`) rather than by a Dart mock of
/// it. That distinction is the whole point: a Dart test that signs with Dart
/// and verifies with Dart proves the two halves of one implementation agree,
/// which is exactly the thing that was never in doubt. What has to hold is
/// that a signature minted by the Node — over a message the Node built — is
/// accepted here, and that everything else is refused.
void main() {
  final fixture = File(
    'test/services/node/fixtures/node_identity_proof_vector.json',
  );
  final vector = jsonDecode(fixture.readAsStringSync()) as Map<String, dynamic>;

  Uint8List b64(String value) =>
      Uint8List.fromList(base64.decode(base64.normalize(value)));
  Uint8List b64url(String value) =>
      Uint8List.fromList(base64Url.decode(base64Url.normalize(value)));
  Uint8List hex(String value) {
    final bytes = Uint8List(value.length ~/ 2);
    for (var i = 0; i < bytes.length; i++) {
      bytes[i] = int.parse(value.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return bytes;
  }

  final pairedPublicKey = b64url(vector['publicKeyBase64Url'] as String);
  final sessionId = vector['sessionId'] as String;
  final nonce = b64(vector['nonceBase64'] as String);
  final challenge = NodeIdentityChallenge(nonce: nonce, sessionId: sessionId);

  Map<String, dynamic> response({
    String? publicKey,
    String? signature,
    String? session,
    String? protocolVersion,
  }) =>
      <String, dynamic>{
        'publicKey': publicKey ?? vector['publicKeyBase64Url'],
        'signature': signature ?? vector['signatureBase64'],
        'sessionId': session ?? sessionId,
        'protocolVersion': protocolVersion ?? vector['protocolVersion'],
        'fingerprint': vector['fingerprint'],
      };

  group('canonical message', () {
    test('is built byte-identically to the Node implementation', () {
      // If this drifts, every signature silently stops verifying and the only
      // symptom is "remote connection never works".
      final built = buildIdentityProofMessage(
        protocolVersion: vector['protocolVersion'] as String,
        sessionId: sessionId,
        nonce: nonce,
        publicKey: pairedPublicKey,
        clientRole: 'client',
      );
      expect(built, equals(hex(vector['canonicalMessageHex'] as String)));
    });

    test('rejects a nonce or key that is not exactly 32 bytes', () {
      for (final badNonce in [Uint8List(0), Uint8List(31), Uint8List(33)]) {
        expect(
          () => buildIdentityProofMessage(
            protocolVersion: 'kubus-node/1',
            sessionId: 's',
            nonce: badNonce,
            publicKey: pairedPublicKey,
            clientRole: 'client',
          ),
          throwsA(isA<NodeIdentityException>()),
        );
      }
      expect(
        () => buildIdentityProofMessage(
          protocolVersion: 'kubus-node/1',
          sessionId: 's',
          nonce: nonce,
          publicKey: Uint8List(31),
          clientRole: 'client',
        ),
        throwsA(isA<NodeIdentityException>()),
      );
    });
  });

  group('fingerprint', () {
    test('derives from the public key exactly as the Node does', () {
      expect(
        nodeFingerprintFromPublicKey(pairedPublicKey),
        equals(vector['fingerprint']),
      );
    });

    test('formats for on-screen comparison', () {
      final formatted = formatNodeFingerprint(vector['fingerprint'] as String);
      expect(formatted, matches(RegExp(r'^[0-9A-F]{4}( [0-9A-F]{4}){3}$')));
      expect(formatted.replaceAll(' ', '').toLowerCase(),
          (vector['fingerprint'] as String).substring(0, 16));
    });
  });

  group('verification', () {
    test('accepts a signature the real Node produced', () async {
      await expectLater(
        verifyNodeIdentityProof(
          challenge: challenge,
          response: response(),
          pairedPublicKey: pairedPublicKey,
        ),
        completes,
      );
    });

    test('rejects a different Node signing the same challenge', () async {
      // The impostor's signature is perfectly valid — for the impostor's key.
      // Verifying against the presented key rather than the paired one would
      // accept this, which is the single most important mistake not to make.
      final imposter = vector['imposter'] as Map<String, dynamic>;
      await expectLater(
        verifyNodeIdentityProof(
          challenge: challenge,
          response: response(
            publicKey: imposter['publicKeyBase64Url'] as String,
            signature: imposter['signatureBase64'] as String,
          ),
          pairedPublicKey: pairedPublicKey,
        ),
        throwsA(
          isA<NodeIdentityException>().having(
            (e) => e.failure,
            'failure',
            NodeIdentityFailure.wrongIdentity,
          ),
        ),
      );
    });

    test('rejects an impostor that claims the paired key it cannot sign for',
        () async {
      final imposter = vector['imposter'] as Map<String, dynamic>;
      await expectLater(
        verifyNodeIdentityProof(
          challenge: challenge,
          // Claims the right identity, signs with the wrong key: exactly what
          // a peer that read the pairing QR but never held the private key
          // can produce.
          response: response(signature: imposter['signatureBase64'] as String),
          pairedPublicKey: pairedPublicKey,
        ),
        throwsA(
          isA<NodeIdentityException>().having(
            (e) => e.failure,
            'failure',
            NodeIdentityFailure.badSignature,
          ),
        ),
      );
    });

    test('rejects a proof replayed into a different session', () async {
      await expectLater(
        verifyNodeIdentityProof(
          challenge: NodeIdentityChallenge(
            nonce: nonce,
            sessionId: 'a-different-session',
          ),
          response: response(),
          pairedPublicKey: pairedPublicKey,
        ),
        throwsA(
          isA<NodeIdentityException>().having(
            (e) => e.failure,
            'failure',
            NodeIdentityFailure.replayed,
          ),
        ),
      );
    });

    test('rejects a proof answering a different nonce', () async {
      // Same session, fresh challenge: a recorded proof must not satisfy it.
      final freshNonce = Uint8List.fromList(List<int>.filled(32, 9));
      await expectLater(
        verifyNodeIdentityProof(
          challenge: NodeIdentityChallenge(
            nonce: freshNonce,
            sessionId: sessionId,
          ),
          response: response(),
          pairedPublicKey: pairedPublicKey,
        ),
        throwsA(
          isA<NodeIdentityException>().having(
            (e) => e.failure,
            'failure',
            NodeIdentityFailure.badSignature,
          ),
        ),
      );
    });

    test('rejects a proof minted under a different protocol version', () async {
      await expectLater(
        verifyNodeIdentityProof(
          challenge: challenge,
          response: response(protocolVersion: 'kubus-node/99'),
          pairedPublicKey: pairedPublicKey,
        ),
        throwsA(
          isA<NodeIdentityException>().having(
            (e) => e.failure,
            'failure',
            NodeIdentityFailure.replayed,
          ),
        ),
      );
    });

    test('rejects malformed shapes before touching the verifier', () async {
      final malformed = <Map<String, dynamic>>[
        response(publicKey: 'not-base64!!'),
        response(signature: 'not-base64!!'),
        response(publicKey: base64Url.encode(List<int>.filled(31, 1))),
        response(signature: base64.encode(List<int>.filled(63, 1))),
        <String, dynamic>{...response()}..remove('signature'),
        <String, dynamic>{...response()}..remove('publicKey'),
        <String, dynamic>{...response(), 'sessionId': 42},
        <String, dynamic>{...response(), 'protocolVersion': null},
      ];
      for (final body in malformed) {
        await expectLater(
          verifyNodeIdentityProof(
            challenge: challenge,
            response: body,
            pairedPublicKey: pairedPublicKey,
          ),
          throwsA(isA<NodeIdentityException>()),
          reason: 'accepted malformed proof: $body',
        );
      }
    });

    test('refuses to verify anything when the device is not paired', () async {
      for (final key in <Uint8List?>[null, Uint8List(31)]) {
        await expectLater(
          verifyNodeIdentityProof(
            challenge: challenge,
            response: response(),
            pairedPublicKey: key,
          ),
          throwsA(
            isA<NodeIdentityException>().having(
              (e) => e.failure,
              'failure',
              NodeIdentityFailure.notPaired,
            ),
          ),
        );
      }
    });
  });

  group('challenge generation', () {
    test('produces a fresh 32-byte nonce every time', () {
      final nonces = List.generate(
        64,
        (_) => NodeIdentityChallenge.generate(sessionId: 's').nonce,
      );
      for (final value in nonces) {
        expect(value, hasLength(32));
      }
      final distinct = nonces.map(base64Encode).toSet();
      expect(distinct, hasLength(64));
    });

    test('carries the nonce and protocol version to the Node', () {
      final generated = NodeIdentityChallenge.generate(sessionId: 'abc');
      final metadata = generated.toRequestMetadata();
      expect(metadata['protocolVersion'], kIdentityProofProtocolVersion);
      expect(base64.decode(metadata['nonce']! as String), hasLength(32));
    });
  });
}
